language: node_js
before_script: npm i -g jshint jscs
script: npm run installify && npm run lint && npm run cover
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "stable"
after_success:
  - npm run coveralls
